cache:
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  paths:
    - .gradle/

build:
  stage: build
  script:
    - cd "$CI_PROJECT_DIR"
    - gradle buildDocker -x test
    - docker tag docker-registry.intr/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME} docker-registry.intr/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_BUILD_REF_NAME}
    - docker rmi docker-registry.intr/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest
